/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch & FocusFlow Semantic Tokens
        "primary": "#004ac6",
        "primary-container": "#2563eb",
        "primary-dark": "#1d4ed8",
        "primary-light": "#3b82f6",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#eeefff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        
        "secondary": "#3755c3",
        "secondary-container": "#708cfd",
        "secondary-fixed": "#dde1ff",
        "secondary-fixed-dim": "#b8c4ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00217a",
        
        "tertiary": "#632ecd",
        "tertiary-container": "#7d4ce7",
        "tertiary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#d0bcff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f6edff",

        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-tint": "#0053db",
        
        "on-surface": "#0b1c30",
        "on-surface-variant": "#434655",
        "outline": "#737686",
        "outline-variant": "#c3c6d7",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",
        
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        // 12 Week Year Time Blocks
        "block-strategic": "#2563eb",
        "block-strategic-bg": "#eff6ff",
        "block-strategic-text": "#1e40af",
        "block-buffer": "#64748b",
        "block-buffer-bg": "#f1f5f9",
        "block-buffer-text": "#334155",
        "block-breakout": "#059669",
        "block-breakout-bg": "#ecfdf5",
        "block-breakout-text": "#065f46",

        // WAM Cadence Thermometer
        "wam-gold": "#10b981",
        "wam-gold-bg": "#d1fae5",
        "wam-alert": "#f59e0b",
        "wam-alert-bg": "#fef3c7",
        "wam-risk": "#ef4444",
        "wam-risk-bg": "#fee2e2",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.375rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
      },
      fontFamily: {
        "display-hero": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "metric-stat": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "body-sm": ["'Inter'", "sans-serif"],
        "label-lg": ["'Inter'", "sans-serif"],
        "label-md": ["'Inter'", "sans-serif"],
        "label-sm": ["'Inter'", "sans-serif"],
        "mono": ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "display-hero": ["48px", { lineHeight: "56px", fontWeight: "800" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", fontWeight: "800" }],
        "headline-xl": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "metric-stat": ["32px", { lineHeight: "38px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "700" }],
      },
      boxShadow: {
        "card": "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px -1px rgba(0, 0, 0, 0.05)",
        "card-elevated": "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.03)",
        "modal": "0 20px 25px -5px rgba(15, 23, 42, 0.1), 0 8px 10px -6px rgba(15, 23, 42, 0.1)",
      }
    },
  },
  plugins: [],
}
